language: cpp
compiler:
    - gcc
    - clang
before_script:
    - mkdir ../build
    - cd ../build
script:
    - cmake ../Practice1609/
    - make -j
    - ./vector/vector
notifications:
    email: false